version: '3'

services:
  php-nginx:
    image: public.ecr.aws/ct-nilus/base-images:nginx-php-dev-v21-noble-8.3
    command: bash -c "php-fpm8.3 && nginx -g 'daemon off;'"
    volumes:
      - .:/var/www/cplatform/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
