version: '3'

services:
  php-nginx:
    image: public.ecr.aws/ct-nilus/base-images:nginx-php-dev-v18-focal-7.4
    command: bash -c "php-fpm7.4 && nginx -g 'daemon off;'"
    volumes:
      - .:/var/www/cplatform/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
